In [35]:
import kaggle

import polars as pl
from polars import DataFrame, col

## Load Data

In [14]:
%%bash

kaggle competitions download -f articles.csv -c h-and-m-personalized-fashion-recommendations -p data
cd data && unzip articles.csv.zip
rm articles.csv.zip

Downloading articles.csv.zip to data

100%|██████████| 4.26M/4.26M [00:01<00:00, 2.69MB/s]

Archive:  articles.csv.zip
  inflating: articles.csv

In [17]:
articles = pl.read_csv("data/articles.csv")
articles.height

105542

In [16]:
articles.head(1)

shape: (1, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ article_i ┆ product_c ┆ prod_name ┆ product_t ┆ … ┆ section_n ┆ garment_g ┆ garment_g ┆ detail_d │
│ d         ┆ ode       ┆ ---       ┆ ype_no    ┆   ┆ ame       ┆ roup_no   ┆ roup_name ┆ esc      │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆           ┆ i64       ┆   ┆ str       ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 108775015 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Womens    ┆ 1002      ┆ Jersey    ┆ Jersey   │
│           ┆           ┆           ┆           ┆   ┆ Everyday  ┆           ┆ Basic     ┆ top with │
│           ┆           ┆           ┆           ┆   ┆ Basics    ┆           ┆           ┆ narrow   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ shoulde… │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Explore

In [27]:
(
    articles
    .group_by("perceived_colour_master_name")
    .len()
    .sort("len", descending=True)
)[:10]

shape: (10, 2)
┌──────────────────────────────┬───────┐
│ perceived_colour_master_name ┆ len   │
│ ---                          ┆ ---   │
│ str                          ┆ u32   │
╞══════════════════════════════╪═══════╡
│ Black                        ┆ 22585 │
│ Blue                         ┆ 18469 │
│ White                        ┆ 12665 │
│ Pink                         ┆ 9403  │
│ Grey                         ┆ 8924  │
│ Red                          ┆ 5878  │
│ Beige                        ┆ 5657  │
│ Green                        ┆ 3526  │
│ Khaki green                  ┆ 3181  │
│ Yellow                       ┆ 3121  │
└──────────────────────────────┴───────┘

In [89]:
subset =  ["Pink", "Grey", "Khaki green", "Yellow", "Black"]

In [90]:
color_subset = (
    articles.filter(col("perceived_colour_master_name").is_in(subset))
)

color_subset

shape: (47_214, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ article_i ┆ product_c ┆ prod_name ┆ product_t ┆ … ┆ section_n ┆ garment_g ┆ garment_g ┆ detail_d │
│ d         ┆ ode       ┆ ---       ┆ ype_no    ┆   ┆ ame       ┆ roup_no   ┆ roup_name ┆ esc      │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆           ┆ i64       ┆   ┆ str       ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 108775015 ┆ 108775    ┆ Strap top ┆ 253       ┆ … ┆ Womens    ┆ 1002      ┆ Jersey    ┆ Jersey   │
│           ┆           ┆           ┆           ┆   ┆ Everyday  ┆           ┆ Basic     ┆ top with │
│           ┆           ┆           ┆           ┆   ┆ Basics    ┆           ┆           ┆ narrow   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ shoulde… │
│ 110065001 ┆ 110065    ┆ OP        ┆ 306       ┆ … ┆ Womens    ┆ 1017      ┆ Under-,   ┆ Microfib │
│           ┆           ┆ T-shirt   ┆           ┆   ┆ Lingerie  ┆           ┆ Nightwear ┆ re       │
│           ┆           ┆ (Idro)    ┆           ┆   ┆           ┆           ┆           ┆ T-shirt  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bra with │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ un…      │
│ 111565001 ┆ 111565    ┆ 20 den 1p ┆ 304       ┆ … ┆ Womens    ┆ 1021      ┆ Socks and ┆ Semi     │
│           ┆           ┆ Stockings ┆           ┆   ┆ Nightwear ┆           ┆ Tights    ┆ shiny    │
│           ┆           ┆           ┆           ┆   ┆ , Socks & ┆           ┆           ┆ nylon    │
│           ┆           ┆           ┆           ┆   ┆ Tigh      ┆           ┆           ┆ stocking │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ s wit…   │
│ 111586001 ┆ 111586    ┆ Shape Up  ┆ 273       ┆ … ┆ Womens    ┆ 1021      ┆ Socks and ┆ Tights   │
│           ┆           ┆ 30 den 1p ┆           ┆   ┆ Nightwear ┆           ┆ Tights    ┆ with     │
│           ┆           ┆ Tights    ┆           ┆   ┆ , Socks & ┆           ┆           ┆ built-in │
│           ┆           ┆           ┆           ┆   ┆ Tigh      ┆           ┆           ┆ support  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ t…       │
│ 111593001 ┆ 111593    ┆ Support   ┆ 304       ┆ … ┆ Womens    ┆ 1021      ┆ Socks and ┆ Semi     │
│           ┆           ┆ 40 den 1p ┆           ┆   ┆ Nightwear ┆           ┆ Tights    ┆ shiny    │
│           ┆           ┆ Tights    ┆           ┆   ┆ , Socks & ┆           ┆           ┆ tights   │
│           ┆           ┆           ┆           ┆   ┆ Tigh      ┆           ┆           ┆ that     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ shape t… │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 952267001 ┆ 952267    ┆ Heavy     ┆ 304       ┆ … ┆ Womens    ┆ 1021      ┆ Socks and ┆ Fine-kni │
│           ┆           ┆ plain     ┆           ┆   ┆ Nightwear ┆           ┆ Tights    ┆ t tights │
│           ┆           ┆ overknee  ┆           ┆   ┆ , Socks & ┆           ┆           ┆ with an  │
│           ┆           ┆ tights 1p ┆           ┆   ┆ Tigh      ┆           ┆           ┆ elast…   │
│ 953450001 ┆ 953450    ┆ 5pk       ┆ 302       ┆ … ┆ Men       ┆ 1021      ┆ Socks and ┆ Socks in │
│           ┆           ┆ regular   ┆           ┆   ┆ Underwear ┆           ┆ Tights    ┆ a fine-k │
│           ┆           ┆ Placement ┆           ┆   ┆           ┆           ┆           ┆ nit      │
│           ┆           ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ cotton   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bl…      │
│ 953763001 ┆ 953763    ┆ SPORT     ┆ 253       ┆ … ┆ H&M+      ┆ 1005      ┆ Jersey    ┆ Loose-fi │
│           ┆           ┆ Malaga    ┆           ┆   ┆           ┆           ┆ Fancy     ┆ tting    │
│           ┆           ┆ tank      ┆           ┆   ┆           ┆           ┆           ┆ sports   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ vest top │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 956217002 ┆ 956217    ┆ Cartwheel ┆ 265       ┆ … ┆ Womens    ┆ 1005      ┆ Jersey    ┆ Short,   │
│           ┆           ┆ dress     ┆           ┆   ┆ Trend     ┆           ┆ Fancy     ┆ A-line   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ dress in │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ jersey … │
│ 957375001 ┆ 957375    ┆ CLAIRE    ┆ 72        ┆ … ┆ Divided   ┆ 1019      ┆ Accessori ┆ Large    │
│           ┆           ┆ HAIR CLAW ┆           ┆   ┆ Accessori ┆           ┆ es        ┆ plastic  │
│           ┆           ┆           ┆           ┆   ┆ es        ┆           ┆           ┆ hair     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ claw.    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
%%timeit

result = (
    articles
    .join(color_subset, on="perceived_colour_master_name", how="inner")
)

In [ ]:
%%timeit

result = (
    articles
    .filter(col("perceived_colour_master_name").is_in(l))
)

In [85]:
N = 100000000

In [86]:
df = pl.DataFrame({"x": pl.Series(range(N))})

In [87]:
%%timeit

df.filter(pl.col("x").is_in(df.select("x").to_series() + 1))

4.89 s ± 62.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [88]:
%%timeit

df.join(df.select("x") + 1, on="x")

4.25 s ± 274 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)